#favourite-api/.github/workflows/promote.yml
name: Promote favourite-api tag

on:
  push:
    tags:
      - 'v*.*.*-rc.*'   # 1.2.0-rc.1 …
      - 'v*.*.*'        # 1.2.0 …

env:
  SERVICE: favourite-api
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_REGION:     ${{ secrets.AWS_REGION }}
  INFRA_REPO:     Sufiyan11919/weather-infra   # ← change if needed
  GH_PAT:         ${{ secrets.PAT_TO_UPDATE_INFRA }}

jobs:
  promote:
    runs-on: ubuntu-latest
    steps:

    - name: Derive tag & sha
      id: vars
      run: |
        echo "TAG=${GITHUB_REF#refs/tags/}"  >> $GITHUB_OUTPUT
        echo "SHA=${GITHUB_SHA}"            >> $GITHUB_OUTPUT

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region:            ${{ env.AWS_REGION }}

    - name: Retag image in ECR (no rebuild)
      env:
        TAG: ${{ steps.vars.outputs.TAG }}
        SHA: ${{ steps.vars.outputs.SHA }}
      run: |
        aws ecr batch-get-image \
          --repository-name $SERVICE --image-ids imageTag=$SHA \
          --query 'images[0].imageManifest' --output text > manifest.json
        aws ecr put-image \
          --repository-name $SERVICE --image-tag $TAG \
          --image-manifest file://manifest.json

    - name: Install GitHub CLI
      run: sudo apt-get update -y && sudo apt-get install -y gh

    - name: Bump tag in infra repo & open PR
      env:
        TAG: ${{ steps.vars.outputs.TAG }}
      run: |
        export GH_TOKEN=$GH_PAT
        git config --global user.name  "promotion-bot"
        git config --global user.email "bot@example.com"

        git clone https://$GH_PAT@github.com/${INFRA_REPO}.git
        cd weather-infra

        ENV_DIR=$( [[ "$TAG" == *"-rc."* ]] && echo uat || echo prod )
        FILE=environments/${ENV_DIR}/${SERVICE}/values.yaml
        BRANCH="bump-${SERVICE}-${TAG}"

        git switch -c "$BRANCH"
        sed -i "s/tag:.*/tag: \"$TAG\"/" "$FILE"
        git commit -am "Promote $SERVICE → $TAG"
        git push -u origin "$BRANCH"

        gh pr create \
          --title  "Promote $SERVICE $TAG" \
          --body   "Automated tag promotion" \
          --head   "$BRANCH" \
          --base   main
