name: Promote weather-frontend tag

on:
  push:
    tags:
      - 'v*.*.*-rc.*'   # RC → UAT

env:
  SERVICE: weather-frontend
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_REGION:     ${{ secrets.AWS_REGION }}
  INFRA_REPO:     Sufiyan11919/weather-infra   # ← update if repo moves
  GH_PAT:         ${{ secrets.PAT_TO_UPDATE_INFRA }}

jobs:
  promote:
    runs-on: ubuntu-latest

    steps:
    - name: Derive tag & sha
      id: vars
      run: |
        echo "TAG=${GITHUB_REF#refs/tags/}"  >> $GITHUB_OUTPUT
        echo "SHA=${GITHUB_SHA}"            >> $GITHUB_OUTPUT

    # ────── AWS creds to retag in ECR ───────────────────────────
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region:            ${{ env.AWS_REGION }}

    - name: Retag ${{ env.SERVICE }} image in ECR
      env:
        TAG: ${{ steps.vars.outputs.TAG }}
        SHA: ${{ steps.vars.outputs.SHA }}
      run: |
        aws ecr batch-get-image \
          --repository-name $SERVICE --image-ids imageTag=$SHA \
          --query 'images[0].imageManifest' --output text > manifest.json
        aws ecr put-image \
          --repository-name $SERVICE --image-tag $TAG \
          --image-manifest file://manifest.json

    # ────── Bump tag in infra repo & open PR ───────────────────
    - name: Install GitHub CLI
      run: sudo apt-get update -y && sudo apt-get install -y gh

    - name: Create bump PR in infra repo
      env:
        TAG: ${{ steps.vars.outputs.TAG }}
      run: |
        export GH_TOKEN=$GH_PAT
        git config --global user.name  "promotion-bot"
        git config --global user.email "bot@example.com"

        git clone https://$GH_PAT@github.com/${INFRA_REPO}.git
        cd weather-infra

        # decide environment dir based on tag
        if [[ "$TAG" == *"-rc."* ]]; then
          ENV_DIR="uat"
        else
          ENV_DIR="prod"
        fi

        FILE=${ENV_DIR}/environments/${SERVICE}/values.yaml   # ← new path
        BRANCH="bump-${SERVICE}-${TAG}"

        git switch -c "$BRANCH"
        sed -i "s|tag:.*|tag: \"$TAG\"|" "$FILE"
        git commit -am "Promote $SERVICE → $TAG"
        git push -u origin "$BRANCH"

        gh pr create \
          --title  "Promote $SERVICE → $TAG" \
          --body   "Automated tag promotion" \
          --head   "$BRANCH" \
          --base   main
