name: Deploy to QA EC2
on:
  workflow_run:
    workflows: [Build & Push]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.QA_EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.QA_EC2_KEY }}
        script: |
          IMAGE_SHA={{ github.event.workflow_run.head_sha }}
          IMAGE="$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/favourite-api:$IMAGE_SHA"
          bash deploy/qa/deploy.sh $IMAGE
